# This is a basic workflow to help you get started with Actions

name: Scanner on push (CMD)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push: #branch github.ref
    branches: [ "main" ]
  #pull_request: #branch github.head_ref
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: git log

      # Runs a set of commands using the runners shell
      - name: Download Xygeni Scanner 
        run: |
          echo Downloading Xygeni Scanner ....
          curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -u ${{ secrets.XY_DEMO_PRUEBAS_USERNAME }} -p ${{ secrets.XY_DEMO_PRUEBAS_PASSWORD }} -s ${{ secrets.XY_DEMO_PRUEBAS_URL }} -d ${GITHUB_WORKSPACE}/scanner
          ls -l


      # Runs a set of commands using the runners shell
      #${GITHUB_WORKSPACE}/scanner/xygeni scan --never-fail -n Xy-${{ github.event.repository.name }}-CMD --dir ${GITHUB_WORKSPACE}/src --all-files
      #${GITHUB_WORKSPACE}/scanner/xygeni inventory  --upload --never-fail -n Xy-${{ github.event.repository.name }}-CMD --dir ${GITHUB_WORKSPACE}/src
      - name: Execution Xygeni Scanner
        run: |
          echo Executing Xygeni scan ....    
          ${GITHUB_WORKSPACE}/scanner/xygeni scan --upload -n GH-${{ github.event.repository.name }}-push-${{ github.ref }}-CMD --dir ${GITHUB_WORKSPACE}/src
          echo =======
          ls -al ${GITHUB_WORKSPACE}/src
          echo =======
          ls -al 
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}




      
